# Starter pipeline
sonar.projectKey=andrewcaio_QA_Andrew
sonar.organization=andrewcaio

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud_test'
    organization: 'andrewcaio'
    scannerMode: 'MSBuild'
    projectKey: 'andrewcaio_QA_Andrew'
    projectName: 'QA_Andrew'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    
trigger:
- task: SonarCloudAnalyze@1
- master

pool:
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
